name: Quarto Publish
on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: example-environment.yml
          python-version: 3.10.4
          channels: defaults, conda-forge

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}